version: 2
jobs:
   build:
     docker:
       - image: circleci/python@sha256:5266fa743b2183588d433073a2eca9b863fb8593475e3f5baa42de8fb68c6f87
     steps:
       - checkout
       - restore_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
       - run:
           name: install geth
           command: |
             wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.10-eae63c51.tar.gz
             tar -xzvf geth-linux-amd64-1.8.10-eae63c51.tar.gz
             sudo mv geth-linux-amd64-1.8.10-eae63c51/geth /usr/local/bin/geth
       - run: sudo apt-get install -y libgmp3-dev
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
       - run: python3 setup.py test
       - save_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
           paths:
             - "venv"
