version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5
     steps:
       - checkout
       - restore_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
       - run: sudo apt-get install -y libgmp3-dev
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
       - run: python3 setup.py test
       - save_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
           paths:
             - "venv"
