version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: install dependencies
          command: |
            apt-get install -y software-properties-common
            add-apt-repository -y ppa:ethereum/ethereum
            apt-get update
            apt-get install -y ethereum
            apt-get install -y libgmp3-dev
            apt-get install -y python3
            apt-get install -y python3-dev
            apt-get install -y python3-venv
            apt-get install -y python3-setuptools
            apt-get install -y pandoc
            apt-get install -y g++
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade 'pip<10'
            pip install web3==4.2.1
      - run:
          command: |
            . venv/bin/activate
            python3 setup.py test
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
